import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";   // ⭐ IMPORTANTE
import { montserrat } from "./fonts";
import WhatsAppButton from "./components/WhatsAppButton";
import "./globals.css";

const font = montserrat;

export const metadata: Metadata = {
  title: "Inventario CP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${font.variable} antialiased bg-white text-neutral-900`}
      >

        {/* ✅ ENVOLTORIO CLIENT SAFE */}
        <Providers>
          {children}
        </Providers>

        <Toaster
          position="top-center"
          toastOptions={{
            duration: 2500,
            style: {
              background: "#111",
              color: "#fff",
              border: "1px solid #333",
              borderRadius: "12px",
              padding: "12px 16px",
            },
          }}
        />

        <WhatsAppButton />

      </body>
    </html>
  );
}
